#!/bin/bash
# Setup script to configure conda environment activation scripts for QLC development
#
#log  "----------------------------------------------------------------------------------------"
#log  "Copyright (c) 2021-2025 ResearchConcepts io GmbH. All Rights Reserved.                  "
#log  "Questions / comments to: Swen M. Metzger <sm@researchconcepts.io>                       "
#log  "----------------------------------------------------------------------------------------"
#
# Usage: bash setup_conda_env.sh [env_name]
#
# This script creates conda activation/deactivation scripts that automatically
# set QLC_HOME when activating the qlc-dev conda environment.

ENV_NAME="${1:-qlc-dev}"
CONDA_PREFIX=$(conda info --base 2>/dev/null)

if [ -z "$CONDA_PREFIX" ]; then
  echo "[ERROR] Conda not found. Please install conda first."
  exit 1
fi

ENV_PATH="$CONDA_PREFIX/envs/$ENV_NAME"

if [ ! -d "$ENV_PATH" ]; then
  echo "[ERROR] Conda environment '$ENV_NAME' not found."
  echo "[INFO] Create it with: conda create -n $ENV_NAME python=3.10"
  exit 1
fi

# Create activation directory
mkdir -p "$ENV_PATH/etc/conda/activate.d"
mkdir -p "$ENV_PATH/etc/conda/deactivate.d"

# Create activation script
cat > "$ENV_PATH/etc/conda/activate.d/qlc-dev-env.sh" << 'EOF'
#!/bin/bash
# Auto-generated by QLC setup_conda_env.sh
# This script automatically sets QLC_HOME when the qlc-dev conda environment is activated

export QLC_HOME="$HOME/qlc-dev-run"
export QLC_DEV_MODE=1
export QLC_SOURCE_DIR="$HOME/qlc-dev"

echo "[QLC-DEV] Development environment activated"
echo "[QLC-DEV] Runtime: $QLC_HOME"
echo "[QLC-DEV] Source: $QLC_SOURCE_DIR"
EOF

# Create deactivation script
cat > "$ENV_PATH/etc/conda/deactivate.d/qlc-dev-env.sh" << 'EOF'
#!/bin/bash
# Auto-generated by QLC setup_conda_env.sh
# This script cleans up QLC environment variables when deactivating

unset QLC_HOME
unset QLC_DEV_MODE
unset QLC_SOURCE_DIR

echo "[QLC-DEV] Development environment deactivated"
EOF

# Make executable
chmod +x "$ENV_PATH/etc/conda/activate.d/qlc-dev-env.sh"
chmod +x "$ENV_PATH/etc/conda/deactivate.d/qlc-dev-env.sh"

echo ""
echo "[SUCCESS] Conda environment '$ENV_NAME' configured for QLC development"
echo ""
echo "Environment activation scripts created:"
echo "  - $ENV_PATH/etc/conda/activate.d/qlc-dev-env.sh"
echo "  - $ENV_PATH/etc/conda/deactivate.d/qlc-dev-env.sh"
echo ""
echo "Test the setup with:"
echo "  conda deactivate"
echo "  conda activate $ENV_NAME"
echo "  echo \$QLC_HOME"
echo "  (should show: $HOME/qlc-dev-run)"
echo ""

