name: Build Multi-Platform Wheels

on:
  push:
    tags:
      - "v*.*.*"  # e.g. v0.3.5
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }} / ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          # Linux
          - os: ubuntu-latest
            arch: x86_64
            cibw_platform: linux
          - os: ubuntu-latest
            arch: aarch64
            cibw_platform: linux

          # macOS
          - os: macos-14  # macos-latest (arm64)
            arch: arm64
            cibw_platform: macos

          # Windows
          - os: windows-latest
            arch: x86_64
            cibw_platform: windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel

      - name: Build wheels with cibuildwheel
        run: |
          cibuildwheel --platform ${{ matrix.cibw_platform }} --arch ${{ matrix.arch }} --output-dir dist
        env:
          CIBW_BUILD: cp310-*         # Only Python 3.10
          CIBW_SKIP: pp*              # Skip PyPy
          CIBW_ENVIRONMENT: CFLAGS="-O2"
          CIBW_ARCHS_MACOS: arm64     # macOS-specific arch control
          CIBW_ARCHS_WINDOWS: AMD64   # Windows-specific arch control

      - name: Upload built wheels
        uses: actions/upload-artifact@v4
        with:
          name: qlc-${{ matrix.os }}-${{ matrix.arch }}
          path: dist/*.whl

      - name: Upload wheels to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.whl

      - name: Set up pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
