name: Publish to PyPI

on:
  release:
    types: [published]  # triggers when a GitHub Release is published

jobs:
  publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Download built wheels from previous job
        uses: actions/download-artifact@v4
        with:
          name: qlc-ubuntu-latest-x86_64  # or loop over all
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
