name: Publish to PyPI

on:
  workflow_run:
    workflows: ["Build Cross-Platform Wheels"]
    types:
      - completed

jobs:
  publish:
    name: Publish wheels to PyPI
    if: github.event.workflow_run.conclusion == 'success' && startsWith(github.event.workflow_run.head_branch, 'v')
    runs-on: ubuntu-latest

    permissions:
      actions: read      # Required to download artifacts from other workflows
      id-token: write  # IMPORTANT: this is required for trusted publishing

    steps:
      - name: Download all wheel artifacts
        uses: actions/download-artifact@v4
        with:
          # The name of the artifact is the name of the workflow that produced it
          # followed by the name of the artifact that was uploaded.
          # We download all artifacts from the completed workflow run.
          name: qlc-wheels-*
          path: dist/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: List downloaded files
        run: ls -R dist

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
