name: Build and Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"  # e.g. v0.3.25
  workflow_dispatch:

jobs:
  build_and_publish:
    name: Build and publish wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]

    environment: pypi  # This is required to match the PyPI trusted publisher configuration

    permissions:
      contents: read   # Needed to checkout the repository
      id-token: write  # IMPORTANT: this is required for trusted publishing to PyPI

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for ARM64 build on Linux)
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgeos-dev proj-bin libproj-dev

      - name: Install system dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install geos proj

      - name: Build wheels via cibuildwheel
        uses: pypa/cibuildwheel@v2.16.5
        env:
          # --- Configure wheel builds ---
          CIBW_BUILD: "cp310-* cp311-*"
          CIBW_SKIP: "*-musllinux_*"
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_BEFORE_ALL_LINUX: "yum install -y epel-release && yum install -y geos-devel proj-devel"
          CIBW_MANYLINUX_X86_64_IMAGE: "manylinux_2_28"
        with:
          # Create wheels in the standard dist/ directory
          output-dir: dist

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # Trusted publishing does not require secrets.
          attestations: false
