name: Publish to PyPI

on:
  workflow_run:
    workflows: ["Build Cross-Platform Wheels"]
    types:
      - completed

jobs:
  publish:
    name: Publish wheels to PyPI
    if: github.event.workflow_run.conclusion == 'success' && startsWith(github.event.workflow_run.head_branch, 'v')
    runs-on: ubuntu-latest
    environment: pypi  # This is required to match the PyPI trusted publisher configuration

    permissions:
      actions: read      # Required to download artifacts from other workflows
      id-token: write  # IMPORTANT: this is required for trusted publishing

    steps:
      - name: Download all wheel artifacts
        uses: actions/download-artifact@v4
        with:
          # When 'name' is not supplied, all artifacts from the workflow run will be downloaded.
          path: dist/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: List downloaded files for debugging
        run: ls -R dist

      - name: Move all wheels to top-level dist directory
        run: find dist -type f -name "*.whl" -exec mv {} dist/ \;

      - name: Clean up empty artifact directories
        run: find dist -mindepth 1 -maxdepth 1 -type d -exec rm -rf {} +

      - name: List final contents of dist for debugging
        run: ls -R dist

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
